import { getOrCreateFoundryId, getUser } from "./foundryUtils";
import { debugLog, displayErrorMessageToUser } from "./logging";
import { getRedirectAddress, postFoundryInfo } from "./server";

async function refreshIpData() : Promise<void> {
    debugLog("Foundry Redirect: Refreshing foundry link data");
    let invitationLinks = new InvitationLinks()
    let invitationData = await invitationLinks.getData();
    debugLog(invitationData);
    let localAddress = invitationData.local;
    let externalAddress = invitationData.remote;

    if(!localAddress){
        displayErrorMessageToUser("Foundry Redirect: Failed to determine local IP address from Foundry")
        return;
    }
    if(!externalAddress) {
        displayErrorMessageToUser("Foundry Redirect: Failed to determine external IP address from Foundry")
        return;
    }
    
    // check if there is a stored foundry id. If not, generate one
    let foundryId = getOrCreateFoundryId();

    // submit the foundry info to AWS
    const p = postFoundryInfo(foundryId, externalAddress, localAddress);

    setTimeout(refreshIpData, 1000 * 60 * 60)
    return p;
}
  
Hooks.on("ready", function() {
    let user = getUser();
    if(!user || !user.isGM){
        console.log("Foundry Redirect: Current user is not the GM. Not setting up foundry redirects");
        return;
    }

    // post server IP to the redirect server
    refreshIpData()
});

Hooks.on("renderInvitationLinks", (links:InvitationLinks, html:JQuery) => {  
    return getRedirectAddress().then(address =>{
        debugLog("Inserting redirect address into invitation links")
        if(!address){
            return;
        }

        const invitationPosition = links.position;
        invitationPosition.height = 200;
        links.setPosition(invitationPosition)

        // find then window content
        const windowContent = html.get(0);
        if(!windowContent){
            debugLog("Could not get base window content")
            console.error("Foundry redirect: Invitation links page does not match expected layout")
            return;
        }

        // When the window is opened from closed, the content of the Jquery argument
        // is the whole window
        // If the window was reloaded, the JQuery is the Form
        let formHtml : HTMLFormElement | undefined;
        if(windowContent.classList.contains("window-app") && windowContent instanceof HTMLDivElement){
            let potentialForm = windowContent.lastElementChild?.lastElementChild;
            if(potentialForm instanceof HTMLFormElement){
                formHtml = potentialForm;
            }
        } else if(windowContent instanceof HTMLFormElement){
            formHtml = windowContent;
        }
        if(!formHtml || formHtml.childElementCount < 3){
            debugLog("Could not locate input form in invitation window")
            debugLog(formHtml)
            debugLog(windowContent.lastElementChild)
            console.error("Foundry redirect: Invitation links page does not match expected layout")
            return;
        }

        const initialNotes = formHtml.children.item(0);
        if(!initialNotes || !(initialNotes instanceof HTMLParagraphElement)) {
            debugLog("Initial form element was not the expected paragraph")
            debugLog(initialNotes)
            return;
        }

        const divToInsert = document.createElement("div")
        const foundryDivId = "foundry-redirect-data"
        divToInsert.id = foundryDivId
        divToInsert.innerHTML = `
            <div class="form-group">
                <label for="local"><i class="fas fa-ethernet"></i> Local Network</label>
                <input type="text" class="invite-link" name="local" value="${address.localAddress}" readonly>
            </div>
            <div class="form-group">
                <label for="remote"><i class="fas fa-wifi"></i> Internet</label>
                <input type="text" style="flex: 3" class="invite-link" name="remote" value="${address.externalAddress}" readonly>
            </div>
            <p class="notes">
                The above links are generated by the Foundry Redirect module. They should remain constant if your IP address changes. To use native FoundryVTT invitation links, see below.
            </p>
            <hr>
        `
        
        formHtml.prepend(divToInsert)
        formHtml.prepend(initialNotes)

        // we need to re-activate the listeners to ensure that the copy functionality works on our new links
        links.activateListeners(html.find(divToInsert));
    });
});
